
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[15]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[16]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[17]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[18]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[19]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[20]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[21]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[22]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[23]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[24]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[25]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[26]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[27]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[28]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[29]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[30]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][0]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][1]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][2]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][3]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][4]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][5]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][6]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][7]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][8]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][9]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][10]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][11]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][12]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][13]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][14]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][15]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][16]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][17]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][18]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][19]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][20]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][21]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][22]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][23]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][24]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][25]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][26]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][27]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][28]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][29]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][30]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[2][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][0]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][1]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][2]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][3]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][4]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][5]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][6]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][7]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][8]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][9]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][10]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][11]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][12]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][13]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][14]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][15]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][16]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][17]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][18]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][19]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][20]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][21]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][22]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][23]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][24]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][25]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][26]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][27]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][28]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][29]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][30]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/artico3_shuffler_0/U0/id_reg[0]} {design_1_i/artico3_shuffler_0/U0/id_reg[1]} {design_1_i/artico3_shuffler_0/U0/id_reg[2]} {design_1_i/artico3_shuffler_0/U0/id_reg[3]} {design_1_i/artico3_shuffler_0/U0/id_reg[4]} {design_1_i/artico3_shuffler_0/U0/id_reg[5]} {design_1_i/artico3_shuffler_0/U0/id_reg[6]} {design_1_i/artico3_shuffler_0/U0/id_reg[7]} {design_1_i/artico3_shuffler_0/U0/id_reg[8]} {design_1_i/artico3_shuffler_0/U0/id_reg[9]} {design_1_i/artico3_shuffler_0/U0/id_reg[10]} {design_1_i/artico3_shuffler_0/U0/id_reg[11]} {design_1_i/artico3_shuffler_0/U0/id_reg[12]} {design_1_i/artico3_shuffler_0/U0/id_reg[13]} {design_1_i/artico3_shuffler_0/U0/id_reg[14]} {design_1_i/artico3_shuffler_0/U0/id_reg[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 4 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/artico3_shuffler_0/U0/id_ack_current[0]} {design_1_i/artico3_shuffler_0/U0/id_ack_current[1]} {design_1_i/artico3_shuffler_0/U0/id_ack_current[2]} {design_1_i/artico3_shuffler_0/U0/id_ack_current[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[0]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[1]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[2]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[3]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[4]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[5]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[6]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[7]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[8]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[9]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[10]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[11]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[12]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[13]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[14]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[15]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[16]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[17]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[18]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[19]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[20]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[21]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[22]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[23]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[24]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[25]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[26]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[27]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[28]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[29]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[30]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_current[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 4 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_en[0]} {design_1_i/artico3_shuffler_0/U0/artico3_en[1]} {design_1_i/artico3_shuffler_0/U0/artico3_en[2]} {design_1_i/artico3_shuffler_0/U0/artico3_en[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/artico3_shuffler_0/U0/engen_state[0]} {design_1_i/artico3_shuffler_0/U0/engen_state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][0]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][1]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][2]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][3]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][4]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][5]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][6]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][7]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][8]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][9]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][10]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][11]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][12]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][13]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][14]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][15]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][16]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][17]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][18]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][19]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][20]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][21]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][22]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][23]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][24]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][25]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][26]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][27]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][28]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][29]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][30]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[3][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 4 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/artico3_shuffler_0/U0/engen_start[0]} {design_1_i/artico3_shuffler_0/U0/engen_start[1]} {design_1_i/artico3_shuffler_0/U0/engen_start[2]} {design_1_i/artico3_shuffler_0/U0/engen_start[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 4 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_mode[0]} {design_1_i/artico3_shuffler_0/U0/artico3_mode[1]} {design_1_i/artico3_shuffler_0/U0/artico3_mode[2]} {design_1_i/artico3_shuffler_0/U0/artico3_mode[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][0]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][1]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][2]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][3]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][4]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][5]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][6]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][7]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][8]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][9]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][10]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][11]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][12]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][13]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][14]} {design_1_i/artico3_shuffler_0/U0/artico3_addr[0][15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 4 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/artico3_shuffler_0/U0/engen_out[0]} {design_1_i/artico3_shuffler_0/U0/engen_out[1]} {design_1_i/artico3_shuffler_0/U0/engen_out[2]} {design_1_i/artico3_shuffler_0/U0/engen_out[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 4 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/artico3_shuffler_0/U0/id_current[0]} {design_1_i/artico3_shuffler_0/U0/id_current[1]} {design_1_i/artico3_shuffler_0/U0/id_current[2]} {design_1_i/artico3_shuffler_0/U0/id_current[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 4 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_we[0]} {design_1_i/artico3_shuffler_0/U0/artico3_we[1]} {design_1_i/artico3_shuffler_0/U0/artico3_we[2]} {design_1_i/artico3_shuffler_0/U0/artico3_we[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][0]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][1]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][2]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][3]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][4]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][5]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][6]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][7]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][8]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][9]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][10]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][11]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][12]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][13]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][14]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][15]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][16]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][17]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][18]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][19]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][20]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][21]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][22]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][23]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][24]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][25]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][26]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][27]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][28]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][29]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][30]} {design_1_i/artico3_shuffler_0/U0/artico3_wdata[0][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 32 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[0]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[1]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[2]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[3]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[4]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[5]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[6]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[7]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[8]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[9]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[10]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[11]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[12]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[13]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[14]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[15]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[16]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[17]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[18]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[19]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[20]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[21]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[22]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[23]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[24]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[25]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[26]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[27]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[28]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[29]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[30]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_max[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 32 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][0]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][1]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][2]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][3]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][4]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][5]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][6]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][7]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][8]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][9]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][10]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][11]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][12]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][13]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][14]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][15]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][16]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][17]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][18]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][19]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][20]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][21]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][22]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][23]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][24]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][25]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][26]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][27]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][28]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][29]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][30]} {design_1_i/artico3_shuffler_0/U0/artico3_rdata[1][31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 4 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_aresetn[0]} {design_1_i/artico3_shuffler_0/U0/artico3_aresetn[1]} {design_1_i/artico3_shuffler_0/U0/artico3_aresetn[2]} {design_1_i/artico3_shuffler_0/U0/artico3_aresetn[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 36 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[0]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[1]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[2]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[3]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[4]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[5]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[6]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[7]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[8]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[9]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[10]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[11]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[12]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[13]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[14]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[15]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[16]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[17]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[18]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[19]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[20]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[21]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[22]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[23]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[24]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[25]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[26]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[27]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[28]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[29]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[30]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[31]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[32]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[33]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[34]} {design_1_i/artico3_shuffler_0/U0/engen_cnt_remaining[35]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 4 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_start[0]} {design_1_i/artico3_shuffler_0/U0/artico3_start[1]} {design_1_i/artico3_shuffler_0/U0/artico3_start[2]} {design_1_i/artico3_shuffler_0/U0/artico3_start[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 2 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_1_i/artico3_shuffler_0/U0/engen_idx[0]} {design_1_i/artico3_shuffler_0/U0/engen_idx[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 4 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {design_1_i/artico3_shuffler_0/U0/id_ack_reg[0]} {design_1_i/artico3_shuffler_0/U0/id_ack_reg[1]} {design_1_i/artico3_shuffler_0/U0/id_ack_reg[2]} {design_1_i/artico3_shuffler_0/U0/id_ack_reg[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 4 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {design_1_i/artico3_shuffler_0/U0/artico3_ready[0]} {design_1_i/artico3_shuffler_0/U0/artico3_ready[1]} {design_1_i/artico3_shuffler_0/U0/artico3_ready[2]} {design_1_i/artico3_shuffler_0/U0/artico3_ready[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 16 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awaddr[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 16 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr_base[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 16 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_araddr[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 16 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr_base[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 16 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awaddr[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 32 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[15]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[16]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[17]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[18]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[19]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[20]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[21]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[22]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[23]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[24]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[25]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[26]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[27]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[28]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[29]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[30]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_din[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 32 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[15]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[16]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[17]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[18]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[19]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[20]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[21]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[22]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[23]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[24]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[25]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[26]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[27]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[28]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[29]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[30]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 32 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[15]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[16]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[17]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[18]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[19]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[20]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[21]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[22]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[23]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[24]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[25]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[26]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[27]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[28]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[29]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[30]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 9 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awlen[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awlen[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awlen[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awlen[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awlen[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awlen[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awlen[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awlen[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awlen[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 32 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[15]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[16]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[17]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[18]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[19]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[20]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[21]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[22]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[23]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[24]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[25]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[26]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[27]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[28]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[29]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[30]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_dout[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 4 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list {design_1_i/artico3_shuffler_0/U0/voter_sel1[0]} {design_1_i/artico3_shuffler_0/U0/voter_sel1[1]} {design_1_i/artico3_shuffler_0/U0/voter_sel1[2]} {design_1_i/artico3_shuffler_0/U0/voter_sel1[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 4 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list {design_1_i/artico3_shuffler_0/U0/voter_sel0[0]} {design_1_i/artico3_shuffler_0/U0/voter_sel0[1]} {design_1_i/artico3_shuffler_0/U0/voter_sel0[2]} {design_1_i/artico3_shuffler_0/U0/voter_sel0[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 32 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list {design_1_i/artico3_shuffler_0/U0/voter_reg0[0]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[1]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[2]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[3]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[4]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[5]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[6]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[7]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[8]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[9]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[10]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[11]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[12]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[13]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[14]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[15]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[16]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[17]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[18]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[19]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[20]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[21]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[22]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[23]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[24]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[25]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[26]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[27]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[28]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[29]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[30]} {design_1_i/artico3_shuffler_0/U0/voter_reg0[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 32 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list {design_1_i/artico3_shuffler_0/U0/voter_reg1[0]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[1]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[2]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[3]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[4]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[5]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[6]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[7]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[8]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[9]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[10]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[11]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[12]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[13]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[14]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[15]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[16]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[17]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[18]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[19]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[20]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[21]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[22]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[23]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[24]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[25]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[26]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[27]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[28]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[29]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[30]} {design_1_i/artico3_shuffler_0/U0/voter_reg1[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 32 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list {design_1_i/artico3_shuffler_0/U0/voter_reg2[0]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[1]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[2]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[3]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[4]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[5]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[6]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[7]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[8]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[9]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[10]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[11]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[12]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[13]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[14]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[15]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[16]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[17]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[18]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[19]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[20]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[21]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[22]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[23]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[24]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[25]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[26]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[27]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[28]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[29]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[30]} {design_1_i/artico3_shuffler_0/U0/voter_reg2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 2 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list {design_1_i/artico3_shuffler_0/U0/voter_num[0]} {design_1_i/artico3_shuffler_0/U0/voter_num[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 4 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list {design_1_i/artico3_shuffler_0/U0/voter_sel2[0]} {design_1_i/artico3_shuffler_0/U0/voter_sel2[1]} {design_1_i/artico3_shuffler_0/U0/voter_sel2[2]} {design_1_i/artico3_shuffler_0/U0/voter_sel2[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 32 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list {design_1_i/artico3_shuffler_0/U0/voter_out[0]} {design_1_i/artico3_shuffler_0/U0/voter_out[1]} {design_1_i/artico3_shuffler_0/U0/voter_out[2]} {design_1_i/artico3_shuffler_0/U0/voter_out[3]} {design_1_i/artico3_shuffler_0/U0/voter_out[4]} {design_1_i/artico3_shuffler_0/U0/voter_out[5]} {design_1_i/artico3_shuffler_0/U0/voter_out[6]} {design_1_i/artico3_shuffler_0/U0/voter_out[7]} {design_1_i/artico3_shuffler_0/U0/voter_out[8]} {design_1_i/artico3_shuffler_0/U0/voter_out[9]} {design_1_i/artico3_shuffler_0/U0/voter_out[10]} {design_1_i/artico3_shuffler_0/U0/voter_out[11]} {design_1_i/artico3_shuffler_0/U0/voter_out[12]} {design_1_i/artico3_shuffler_0/U0/voter_out[13]} {design_1_i/artico3_shuffler_0/U0/voter_out[14]} {design_1_i/artico3_shuffler_0/U0/voter_out[15]} {design_1_i/artico3_shuffler_0/U0/voter_out[16]} {design_1_i/artico3_shuffler_0/U0/voter_out[17]} {design_1_i/artico3_shuffler_0/U0/voter_out[18]} {design_1_i/artico3_shuffler_0/U0/voter_out[19]} {design_1_i/artico3_shuffler_0/U0/voter_out[20]} {design_1_i/artico3_shuffler_0/U0/voter_out[21]} {design_1_i/artico3_shuffler_0/U0/voter_out[22]} {design_1_i/artico3_shuffler_0/U0/voter_out[23]} {design_1_i/artico3_shuffler_0/U0/voter_out[24]} {design_1_i/artico3_shuffler_0/U0/voter_out[25]} {design_1_i/artico3_shuffler_0/U0/voter_out[26]} {design_1_i/artico3_shuffler_0/U0/voter_out[27]} {design_1_i/artico3_shuffler_0/U0/voter_out[28]} {design_1_i/artico3_shuffler_0/U0/voter_out[29]} {design_1_i/artico3_shuffler_0/U0/voter_out[30]} {design_1_i/artico3_shuffler_0/U0/voter_out[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 4 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list {design_1_i/artico3_shuffler_0/U0/voter_en[0]} {design_1_i/artico3_shuffler_0/U0/voter_en[1]} {design_1_i/artico3_shuffler_0/U0/voter_en[2]} {design_1_i/artico3_shuffler_0/U0/voter_en[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 16 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_araddr[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 9 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 9 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen_addr[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen_addr[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen_addr[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen_addr[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen_addr[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen_addr[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen_addr[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen_addr[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arlen_addr[8]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 32 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[0]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[1]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[2]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[3]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[4]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[5]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[6]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[7]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[8]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[9]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[10]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[11]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[12]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[13]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[14]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[15]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[16]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[17]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[18]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[19]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[20]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[21]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[22]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[23]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[24]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[25]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[26]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[27]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[28]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[29]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[30]} {design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rdata[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe47]
set_property port_width 1 [get_debug_ports u_ila_0/probe47]
connect_debug_port u_ila_0/probe47 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe48]
set_property port_width 1 [get_debug_ports u_ila_0/probe48]
connect_debug_port u_ila_0/probe48 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe49]
set_property port_width 1 [get_debug_ports u_ila_0/probe49]
connect_debug_port u_ila_0/probe49 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe50]
set_property port_width 1 [get_debug_ports u_ila_0/probe50]
connect_debug_port u_ila_0/probe50 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe51]
set_property port_width 1 [get_debug_ports u_ila_0/probe51]
connect_debug_port u_ila_0/probe51 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe52]
set_property port_width 1 [get_debug_ports u_ila_0/probe52]
connect_debug_port u_ila_0/probe52 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe53]
set_property port_width 1 [get_debug_ports u_ila_0/probe53]
connect_debug_port u_ila_0/probe53 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe54]
set_property port_width 1 [get_debug_ports u_ila_0/probe54]
connect_debug_port u_ila_0/probe54 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe55]
set_property port_width 1 [get_debug_ports u_ila_0/probe55]
connect_debug_port u_ila_0/probe55 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe56]
set_property port_width 1 [get_debug_ports u_ila_0/probe56]
connect_debug_port u_ila_0/probe56 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rlast_addr]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe57]
set_property port_width 1 [get_debug_ports u_ila_0/probe57]
connect_debug_port u_ila_0/probe57 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe58]
set_property port_width 1 [get_debug_ports u_ila_0/probe58]
connect_debug_port u_ila_0/probe58 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe59]
set_property port_width 1 [get_debug_ports u_ila_0/probe59]
connect_debug_port u_ila_0/probe59 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe60]
set_property port_width 1 [get_debug_ports u_ila_0/probe60]
connect_debug_port u_ila_0/probe60 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe61]
set_property port_width 1 [get_debug_ports u_ila_0/probe61]
connect_debug_port u_ila_0/probe61 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_rvalid_addr]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe62]
set_property port_width 1 [get_debug_ports u_ila_0/probe62]
connect_debug_port u_ila_0/probe62 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rvalid_base]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe63]
set_property port_width 1 [get_debug_ports u_ila_0/probe63]
connect_debug_port u_ila_0/probe63 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rvalid_ext]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe64]
set_property port_width 1 [get_debug_ports u_ila_0/probe64]
connect_debug_port u_ila_0/probe64 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rvalid_redctrl]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe65]
set_property port_width 1 [get_debug_ports u_ila_0/probe65]
connect_debug_port u_ila_0/probe65 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_rvalid_regctrl]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe66]
set_property port_width 1 [get_debug_ports u_ila_0/probe66]
connect_debug_port u_ila_0/probe66 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe67]
set_property port_width 1 [get_debug_ports u_ila_0/probe67]
connect_debug_port u_ila_0/probe67 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe68]
set_property port_width 1 [get_debug_ports u_ila_0/probe68]
connect_debug_port u_ila_0/probe68 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe69]
set_property port_width 1 [get_debug_ports u_ila_0/probe69]
connect_debug_port u_ila_0/probe69 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_control/axi_wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe70]
set_property port_width 1 [get_debug_ports u_ila_0/probe70]
connect_debug_port u_ila_0/probe70 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/axi_wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe71]
set_property port_width 1 [get_debug_ports u_ila_0/probe71]
connect_debug_port u_ila_0/probe71 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe72]
set_property port_width 1 [get_debug_ports u_ila_0/probe72]
connect_debug_port u_ila_0/probe72 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe73]
set_property port_width 1 [get_debug_ports u_ila_0/probe73]
connect_debug_port u_ila_0/probe73 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_ren]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe74]
set_property port_width 1 [get_debug_ports u_ila_0/probe74]
connect_debug_port u_ila_0/probe74 [get_nets [list design_1_i/artico3_shuffler_0/U0/shuffler_data/fifo_wen]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe75]
set_property port_width 1 [get_debug_ports u_ila_0/probe75]
connect_debug_port u_ila_0/probe75 [get_nets [list design_1_i/artico3_shuffler_0/U0/addr_capture]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe76]
set_property port_width 1 [get_debug_ports u_ila_0/probe76]
connect_debug_port u_ila_0/probe76 [get_nets [list design_1_i/artico3_shuffler_0/U0/addr_reset]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
